### ISSUE TITLE
Patch on Wine

### ISSUE THREAD

**Issue by SanZamoyski** [DCxDemo/THPS2-Cumulative-Patch#29]
Hi!

I'm using Wine on linux to play THPS2. 
I tried Windows XP in VirtualBox but as far as I understand it won't work since VB does not support DirectX 7 (dxdiag confirms that, only 8 and 9 are supported) - I get blank screen. Also tried vmware, but it was uplayable.
So, everything seems to work on wine at least widescreen and gameplay but, when I select ie. THPS1 levels I get THPS2 only.
I installed THPS2 from iso, th2patch_v4prev2.7z, th2_content_pack.7z, and crack.

I don't know where to look for anything more.

[THPCERR.LOG](https://github.com/DCxDemo/THPS2-Cumulative-Patch/files/9289558/THPCERR.LOG)
[TH2_OPT.CFG.txt](https://github.com/DCxDemo/THPS2-Cumulative-Patch/files/9289564/TH2_OPT.CFG.txt)

Thanks in advance!

**Comment by DCxDemo** [comment]
try to use dinput.dll from the latest release here, i think it might be related to the fact the old release relies on .net launcher that accesses thawk2.exe process, that might not work properly on linux, not like that ever intended to be run on linux anyways, but if it'll work, thats great. latest one patches level names in the dll, so probably it will work since you say widescreen works, but gaps/newtex names weren't moved to dll yet so that functionality work.

**Comment by PMKrol** [comment]
Unfortunately, it didn't help. Any way to debug it somehow?
[THPCERR.LOG](https://github.com/DCxDemo/THPS2-Cumulative-Patch/files/9338600/THPCERR.LOG)

I have .Net 4.0 or 4.5 installed in Wine.

**Comment by SanZamoyski** [comment]
Unfortunately, it didn't help. Any way to debug it somehow?
[THPCERR.LOG](https://github.com/DCxDemo/THPS2-Cumulative-Patch/files/9338600/THPCERR.LOG)

I have .Net 4.0 or 4.5 installed in Wine.

**Comment by SanZamoyski** [comment]
Are there any debug switches for this patch I can try?

**Comment by SanZamoyski** [comment]
I've found that I need to force dll with widescreen from THPS3.
Tried that with THPS2 - it won't start. These are debug messages:
[thps2-forcedll.txt](https://github.com/DCxDemo/THPS2-Cumulative-Patch/files/9453621/thps2-forcedll.txt)

**Comment by SanZamoyski** [comment]
Yes!
It works well now.
thps.db was non-zero size (80 KiB), but replacing dll worked.

Thank You!
